name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.5.2
  - pip=20.3.3
  - mlflow=1.30.0
  - scikit-learn=0.24.1
  - matplotlib=3.6.2
  - pillow=8.1.2
  - pip:
      - wandb==0.13.7
