name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - seaborn=0.11.1
  - pandas=1.5.2
  - pip=22.3.1
  - pandas-profiling=3.6.1
  - pyarrow=2.0
  - pip:
      - wandb==0.13.7